---

# WAN CV Pathfinder Settings

fabric_name: WAN
use_anta: true
deploy_to_cv_accept_preview: true
deploy_to_cv_inventory_host: cloudvision
bgp_update_wait_install: false
wan_stun_dtls_disable: true

wan_mode: cv-pathfinder

bgp_as: 65199

cv_pathfinder_regions:
  - name: cvn18_region1
    id: 11
    sites:
      - name: Site-Hub-A1
        id: 111
        location: New Delhi, India, India
      - name: Site-Hub-A2
        id: 112
        location: Kolkata, India, India
      - name: Site-Edge-A1
        id: 113
        location: Mumbai, India, India
      - name: Site-Edge-A2
        id: 114
        location: Bengaluru, India, India         
  - name: cvn18_region2
    id: 12
    sites:
      - name: Site-Hub-B1 
        id: 121
        location: Bangkok, Thailand, Thailand
      - name: Site-Hub-B2
        id: 122
        location: Manila, Philippines, Philippines
      - name: Site-Edge-B1
        id: 123
        location: Singapore, Singapore, Singapore
      - name: Site-Edge-B2
        id: 124
        location: Kuching, Malaysia, Malaysia


bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.118.0/30
      - 192.168.119.0/30
      - 192.168.218.0/30
      - 192.168.219.0/30


wan_route_servers:
  - hostname: cvn18-pf1
  - hostname: cvn18-pf2

wan_ipsec_profiles:
  control_plane:
    shared_key: 0110100A480E0A0E231D1E
  data_plane:
    shared_key: 0110100A480E0A0E231D1E

wan_path_groups:
  - name: internet1
    id: 181
  - name: mpls1
    id: 182

wan_carriers:
  - name: internet1
    path_group: internet1
    trusted: True
  - name: mpls1
    path_group: mpls1
    trusted: True

wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
      wan_vni: 181
    - name: prod
      policy: PROD-AVT-POLICY
      wan_vni: 182
    - name: dev
      policy: DEV-AVT-POLICY
      wan_vni: 183

  policies:
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [internet1]
            preference: preferred
          - names: [mpls1]
            preference: preferred
    - name: DEV-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [internet1]
            preference: alternate
          - names: [mpls1]
            preference: preferred
    - name: PROD-AVT-POLICY
      application_virtual_topologies:
        - application_profile: IT-APP
          id: 6
          traffic_class: 3
          dscp: 26
          constraints:
            latency: 30
          path_groups:
            - names: [internet1]
              preference: preferred
            - names: [mpls1]
              preference: alternate

        - application_profile: Critical-APP
          id: 5
          traffic_class: 2
          dscp: 18
          path_groups:
            - names: [internet1]
              preference: alternate
            - names: [mpls1]
              preference: preferred

        - application_profile: Voice
          id: 4
          traffic_class: 5
          dscp: 46
          path_groups:
            - names: [internet1]
              preference: alternate
            - names: [mpls1]
              preference: preferred

      default_virtual_topology:
        traffic_class: 0
        dscp: 24
        constraints:
          latency: 15
          jitter: 3000
        path_groups:
          - names: [internet1]
            preference: preferred
          - names: [mpls1]
            preference: preferred


application_classification:
  field_sets:
    l4_ports:
      - name: IT-AppDstPorts
        port_values:
          -  '5003'
      - name: Critical-AppDstPorts
        port_values:
          -  '22'
    ipv4_prefixes:
      - name: IT-AppSrcPrefixes
        prefix_values:
          - 172.29.2.22/32
      - name: Critical-AppSrcPrefixes
        prefix_values:
          - 172.29.5.55/32
      - name: VoiceHostsDstPrefixes
        prefix_values:
          - 172.29.4.44/32
          - 172.29.144.44/32
      - name: VoiceHostsSrcPrefixes
        prefix_values:
          - 172.29.4.44/32
          - 172.29.144.44/32
  applications:
    ipv4_applications:
      - name: IT-App
        src_prefix_set_name: IT-AppSrcPrefixes
        protocols:
          - 'tcp'
        tcp_dest_port_set_name: IT-AppDstPorts
      - name: Critical-App
        src_prefix_set_name: Critical-AppSrcPrefixes
        protocols:
          - 'tcp'
        tcp_dest_port_set_name: Critical-AppDstPorts
      - name: Voice
        dest_prefix_set_name: VoiceHostsDstPrefixes
        src_prefix_set_name: VoiceHostsSrcPrefixes

  application_profiles:
    - name: IT-APP
      applications:
        - name: IT-App
        - name: iperf
    - name: Critical-APP
      applications:
        - name: Critical-App
    - name: Voice
      applications:
        - name: Voice
