---

# WAN Transit Nodes

type: wan_router

wan_router:  # dynamic_key: node_type
  defaults:
    id: 1
    loopback_ipv4_offset: -1
    cv_pathfinder_region: cvn18_region1
    cv_pathfinder_transit_mode: region
    filter:
      always_include_vrfs_in_tenants: [cvnselab18]
  nodes:
    - name: cvn18-tr-a1
      cv_pathfinder_region: cvn18_region1
      cv_pathfinder_site: Site-Hub-A1
      loopback_ipv4_pool: 10.254.118.1/32
      vtep_loopback_ipv4_pool: 192.168.118.1/32
      mgmt_ip: 10.90.245.90/24
      l3_interfaces:
        - name: Ethernet1
          ip_address: 10.90.248.3/24
          wan_carrier: internet1
          wan_circuit_id: TR-A1-INET-3
        - name: Ethernet8
          ip_address: 172.29.18.3/24
          wan_carrier: mpls1
          wan_circuit_id: TR-A1-MPLS-3
    - name: cvn18-tr-a2
      cv_pathfinder_region: cvn18_region1
      cv_pathfinder_site: Site-Hub-A2
      mgmt_ip: 10.90.245.51/24
      loopback_ipv4_pool: 10.254.118.2/32
      vtep_loopback_ipv4_pool: 192.168.118.2/32
      l3_interfaces:
        - name: Ethernet1
          ip_address: 10.90.248.4/24
          wan_carrier: internet1
          wan_circuit_id: TR-A2-INET-4
        - name: Ethernet8
          ip_address: 172.29.18.4/24
          wan_carrier: mpls1
          wan_circuit_id: TR-A2-MPLS-4
    - name: cvn18-tr-b1
      cv_pathfinder_region: cvn18_region2
      cv_pathfinder_site: Site-Hub-B1
      mgmt_ip: 10.90.245.97/24
      loopback_ipv4_pool: 10.254.119.1/32
      vtep_loopback_ipv4_pool: 192.168.119.1/32
      l3_interfaces:
        - name: Ethernet1
          ip_address: 10.90.248.5/24
          wan_carrier: internet1
          wan_circuit_id: TR-B1-INET-5
        - name: Ethernet8
          ip_address: 172.29.18.5/24
          wan_carrier: mpls1
          wan_circuit_id: TR-B1-MPLS-5
    - name: cvn18-tr-b2
      cv_pathfinder_region: cvn18_region2
      cv_pathfinder_site: Site-Hub-B2
      mgmt_ip: 10.90.245.99/24
      loopback_ipv4_pool: 10.254.119.2/32
      vtep_loopback_ipv4_pool: 192.168.119.2/32
      l3_interfaces:
        - name: Ethernet1
          ip_address: 10.90.248.6/24
          wan_carrier: internet1
          wan_circuit_id: TR-B2-INET-6
        - name: Ethernet8
          ip_address: 172.29.18.6/24
          wan_carrier: mpls1
          wan_circuit_id: TR-B2-MPLS-6
