---

# cvn10-Site-Tier1-2 Router Configuration

# custom_structured_configuration_router_path_selection:
#   path_groups:
#     - name: LAN_HA
#       id: 65530
#       local_interfaces:
#         - name: Ethernet7
#         # - name: Ethernet7
#       ipsec_profile: CP-PROFILE
#       flow_assignment: lan
#       static_peers:
#         - router_ip: 192.168.218.1
#           ipv4_addresses:
#             - 172.29.217.3
#             # - 172.29.9.3

custom_structured_configuration_ethernet_interfaces:
# - name: Ethernet6
#   mtu: 1600
#   description: "LAN HA Interface"
#   ip_address: 172.29.9.4/29
#   shutdown: false
#   type: routed
#   flow_tracker:
#     hardware: FLOW-TRACKER
# - name: Ethernet7
#   mtu: 1600
#   description: "LAN HA Interface"
#   ip_address: 172.29.217.4/29
#   shutdown: false
#   type: routed
#   flow_tracker:
#     hardware: FLOW-TRACKER
- name: Ethernet1
  mtu: 1500
  flow_tracker:
    hardware: FLOW-TRACKER
- name: Ethernet4
  ip_address: 172.29.4.1/24
  shutdown: false
  vrf: prod
  type: routed
  flow_tracker:
    hardware: FLOW-TRACKER
- name: Ethernet5
  ip_address: 172.29.5.1/24
  shutdown: false
  vrf: dev
  type: routed
  flow_tracker:
    hardware: FLOW-TRACKER
- name: Ethernet8
  mtu: 1700
  flow_tracker:
    hardware: FLOW-TRACKER
